databases:
  - name: veue
    databaseName: veue
    user: veue

services:
  - type: web
    name: veue
    env: docker
    # dockerCommand is optional.
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: veue
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
